# Generated by Django 2.2.6 on 2019-10-05 19:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoorStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('UNKNOWN', 'unknown'), ('OPEN', 'open'), ('CLOSE', 'close')], max_length=255)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
