# Generated by Django 2.2.6 on 2020-10-23 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doorlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doorstatus',
            name='status',
            field=models.CharField(choices=[('unknown', 'unknown'), ('open', 'open'), ('close', 'close')], max_length=255),
        ),
    ]
