# Generated by Django 2.2.6 on 2019-10-07 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
