# Generated by Django 2.2.6 on 2019-10-07 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191007_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='value',
            field=models.FloatField(),
        ),
    ]
