# Generated by Django 2.2.6 on 2019-10-07 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191007_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='name',
            field=models.CharField(choices=[('temperature', 'temperature'), ('humidity', 'humidity'), ('barometer', 'barometer')], max_length=255),
        ),
    ]
