# Generated by Django 2.2.6 on 2019-10-08 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191007_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='type',
            field=models.CharField(choices=[('temperature', 'temperature'), ('humidity', 'humidity'), ('barometer', 'barometer')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
