# Generated by Django 2.2.6 on 2019-10-08 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20191008_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
