# Generated by Django 2.2.6 on 2019-10-08 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20191008_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
