# Generated by Django 2.2.6 on 2019-10-20 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_sensordata_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='type',
            field=models.CharField(choices=[('temperature', 'temperature'), ('humidity', 'humidity'), ('barometer', 'barometer'), ('beta_gamma', 'beta_gamma')], max_length=255, null=True),
        ),
    ]
