# Generated by Django 2.2.6 on 2019-11-06 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20191020_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='type',
            field=models.CharField(choices=[('temperature', 'temperature'), ('humidity', 'humidity'), ('barometer', 'barometer'), ('beta_gamma', 'beta_gamma'), ('total_member_count', 'total_member_count')], max_length=255, null=True),
        ),
    ]
