# Generated by Django 2.2.6 on 2020-10-26 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20201026_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='type',
            field=models.CharField(choices=[('temperature', 'temperature'), ('humidity', 'humidity'), ('barometer', 'barometer'), ('beta_gamma', 'beta_gamma'), ('total_member_count', 'total_member_count'), ('carbondioxide', 'carbondioxide'), ('max_persons_in_space', 'max_persons_in_space')], max_length=255, null=True),
        ),
    ]
